USE DINE_APP
go

CREATE TABLE DINE_CLASSSUB (
   CLASSID              VARCHAR(36)          NOT NULL,
   DINE_ID              VARCHAR(36)          NULL,
   CLASSNAME            VARCHAR(50)          NULL,
   COOKNOTEGID          VARCHAR(36)          NULL,
   CONSTRAINT PK_DINE_CLASSSUB PRIMARY KEY (CLASSID)
)
go

IF EXISTS (SELECT 1 FROM  SYS.EXTENDED_PROPERTIES
           WHERE MAJOR_ID = OBJECT_ID('DINE_CLASSSUB') AND MINOR_ID = 0)
BEGIN 
   DECLARE @CURRENTUSER SYSNAME 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description',  
   'user', @CURRENTUSER, 'table', 'DINE_CLASSSUB' 
 
END 


SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description',  
   '������ϵͳ��ͬ����', 
   'user', @CURRENTUSER, 'table', 'DINE_CLASSSUB'
go

CREATE TABLE DINE_GOODSBOM (
   TABLEID              VARCHAR(36)          NOT NULL,
   GOODSID              VARCHAR(36)          NOT NULL,
   GOODSIDS             VARCHAR(36)          NOT NULL,
   QTY                  DECIMAL(10,2)        NOT NULL,
   UNIT                 VARCHAR(50)          NOT NULL,
   CONSTRAINT PK_DINE_GOODSBOM PRIMARY KEY (TABLEID)
)
go

IF EXISTS (SELECT 1 FROM  SYS.EXTENDED_PROPERTIES
           WHERE MAJOR_ID = OBJECT_ID('DINE_GOODSBOM') AND MINOR_ID = 0)
BEGIN 
   DECLARE @CURRENTUSER SYSNAME 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description',  
   'user', @CURRENTUSER, 'table', 'DINE_GOODSBOM' 
 
END 


SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description',  
   '������ϵͳ��ͬ����', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODSBOM'
go

CREATE TABLE DINE_GOODS (
   GOODSID              VARCHAR(36)          NOT NULL,
   DINE_ID              VARCHAR(36)          NULL,
   GOODSCODE            VARCHAR(50)          NULL,
   GOODSNAME            VARCHAR(200)         NULL,
   UNIT                 VARCHAR(20)          NULL,
   PRICE                DECIMAL(10,2)        NULL,
   CLASSID              VARCHAR(36)          NULL,
   COOKNOTEGID          VARCHAR(36)          NULL,
   GOODSIMAGE           VARCHAR(200)         NULL,
   GOODSKEYWORD         VARCHAR(500)         NULL,
   GOODSREMARK          VARCHAR(MAX)         NULL,
   PROPERTY             INT                  NULL,
   STATUS               INT                  NULL,
   CREATED_BY           VARCHAR(36)          NULL,
   CREATED_TIME         DATETIME             NULL DEFAULT GETDATE(),
   LAST_UPDATED_BY      VARCHAR(36)          NULL,
   LAST_UPDATED_TIME    DATETIME             NULL DEFAULT GETDATE(),
   CONSTRAINT PK_DINE_GOODS PRIMARY KEY (GOODSID)
)
go

IF EXISTS (SELECT 1 FROM  SYS.EXTENDED_PROPERTIES
           WHERE MAJOR_ID = OBJECT_ID('DINE_GOODS') AND MINOR_ID = 0)
BEGIN 
   DECLARE @CURRENTUSER SYSNAME 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description',  
   'user', @CURRENTUSER, 'table', 'DINE_GOODS' 
 
END 


SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description',  
   '������ϵͳ��ͬ����
   
   MEALSETFLAG,       --Ĭ��0  �ײͱ�ʶ�ֶ�,��ƷĬ��Ϊ0,�ײ���ƷΪ-1,�ײ����Ʒ--��ֵ��Ӧ�ײ���Ʒ�� GoodsNo�ֶ�ֵ', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_GOODS')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS', 'column', 'CREATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '������',
   'user', @CURRENTUSER, 'table', 'DINE_GOODS', 'column', 'CREATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_GOODS')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS', 'column', 'CREATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_GOODS', 'column', 'CREATED_TIME'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_GOODS')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS', 'column', 'LAST_UPDATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸���',
   'user', @CURRENTUSER, 'table', 'DINE_GOODS', 'column', 'LAST_UPDATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_GOODS')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS', 'column', 'LAST_UPDATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸�ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_GOODS', 'column', 'LAST_UPDATED_TIME'
go

CREATE TABLE DINE_GOODSCOOKNOTE (
   TABLEID              VARCHAR(36)          NOT NULL,
   GOODSID              VARCHAR(36)          NOT NULL,
   COOKNOTEID           VARCHAR(36)          NOT NULL,
   CONSTRAINT PK_DINE_GOODSCOOKNOTE PRIMARY KEY (TABLEID)
)
go

IF EXISTS (SELECT 1 FROM  SYS.EXTENDED_PROPERTIES
           WHERE MAJOR_ID = OBJECT_ID('DINE_GOODSCOOKNOTE') AND MINOR_ID = 0)
BEGIN 
   DECLARE @CURRENTUSER SYSNAME 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description',  
   'user', @CURRENTUSER, 'table', 'DINE_GOODSCOOKNOTE' 
 
END 


SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description',  
   '������ϵͳ��ͬ����', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODSCOOKNOTE'
go

CREATE TABLE DINE_GOODS_TYPE (
   TYPEID               VARCHAR(36)          NOT NULL,
   DINE_ID              VARCHAR(36)          NULL,
   TYPENAME             VARCHAR(100)         NULL,
   TYPEENAME            VARCHAR(100)         NULL,
   CLASSREMARK          VARCHAR(500)         NULL,
   CLASSORDER           INT                  NULL,
   STATUS               INT                  NULL,
   CREATED_BY           VARCHAR(36)          NULL,
   CREATED_TIME         DATETIME             NULL DEFAULT GETDATE(),
   LAST_UPDATED_BY      VARCHAR(36)          NULL,
   LAST_UPDATED_TIME    DATETIME             NULL DEFAULT GETDATE(),
   CONSTRAINT PK_DINE_GOODS_TYPE PRIMARY KEY (TYPEID)
)
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_GOODS_TYPE')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS_TYPE', 'column', 'CREATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '������',
   'user', @CURRENTUSER, 'table', 'DINE_GOODS_TYPE', 'column', 'CREATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_GOODS_TYPE')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS_TYPE', 'column', 'CREATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_GOODS_TYPE', 'column', 'CREATED_TIME'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_GOODS_TYPE')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS_TYPE', 'column', 'LAST_UPDATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸���',
   'user', @CURRENTUSER, 'table', 'DINE_GOODS_TYPE', 'column', 'LAST_UPDATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_GOODS_TYPE')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_GOODS_TYPE', 'column', 'LAST_UPDATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸�ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_GOODS_TYPE', 'column', 'LAST_UPDATED_TIME'
go

CREATE TABLE DINE_GOODS_TYPE_REL (
   RELATIONID           VARCHAR(36)          NOT NULL,
   TYPEID               VARCHAR(36)          NOT NULL,
   GOODSID              VARCHAR(36)          NOT NULL,
   CONSTRAINT PK_DINE_GOODS_TYPE_REL PRIMARY KEY (RELATIONID)
)
go

CREATE TABLE DINE_MAIN (
   DINE_ID              VARCHAR(36)          NOT NULL,
   DINE_NAME            VARCHAR(200)         NULL,
   DINE_ENAME           VARCHAR(200)         NULL,
   DINE_CALLNUMBER_SETTING VARCHAR(200)         NULL,
   INTEGRAL_EXCHANGE_RATIO DECIMAL(5,1)         NULL DEFAULT 0,
   DINE_PHOTO_URL       VARCHAR(200)         NULL,
   LOCATION_ADDR        VARCHAR(200)         NULL,
   LOCATION_EADDR       VARCHAR(500)         NULL,
   LOCATION_LATITUDE    DECIMAL(12, 7)       NULL,
   LOCATION_LONGITUDE   DECIMAL(12, 7)       NULL,
   STATUS               INT                  NULL,
   CREATED_BY           VARCHAR(36)          NULL,
   CREATED_TIME         DATETIME             NULL DEFAULT GETDATE(),
   LAST_UPDATED_BY      VARCHAR(36)          NULL,
   LAST_UPDATED_TIME    DATETIME             NULL DEFAULT GETDATE(),
   CONSTRAINT PK_DINE_MAIN PRIMARY KEY (DINE_ID)
)
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_MAIN')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LOCATION_LATITUDE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'LOCATION_LATITUDE'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '������',
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'LOCATION_LATITUDE'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_MAIN')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LOCATION_LONGITUDE')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'LOCATION_LONGITUDE'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '������',
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'LOCATION_LONGITUDE'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_MAIN')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'CREATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '������',
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'CREATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_MAIN')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'CREATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'CREATED_TIME'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_MAIN')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'LAST_UPDATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸���',
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'LAST_UPDATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_MAIN')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'LAST_UPDATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸�ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_MAIN', 'column', 'LAST_UPDATED_TIME'
go

CREATE TABLE DINE_COOKNOTE (
   COOKNOTEID           VARCHAR(36)          NOT NULL,
   DINE_ID              VARCHAR(36)          NULL,
   COOKNOTENAME         VARCHAR(50)          NULL,
   COOKNOTEGID          VARCHAR(36)          NULL,
   CONSTRAINT PK_DINE_COOKNOTE PRIMARY KEY (COOKNOTEID)
)
go

IF EXISTS (SELECT 1 FROM  SYS.EXTENDED_PROPERTIES
           WHERE MAJOR_ID = OBJECT_ID('DINE_COOKNOTE') AND MINOR_ID = 0)
BEGIN 
   DECLARE @CURRENTUSER SYSNAME 
SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description',  
   'user', @CURRENTUSER, 'table', 'DINE_COOKNOTE' 
 
END 


SELECT @CURRENTUSER = USER_NAME() 
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description',  
   '������ϵͳ��ͬ����', 
   'user', @CURRENTUSER, 'table', 'DINE_COOKNOTE'
go

CREATE TABLE DINE_SALES (
   SALESID              VARCHAR(36)          NOT NULL,
   DINE_ID              VARCHAR(36)          NULL,
   SALESCODE            VARCHAR(50)          NULL,
   BEGINDATE            DATE                 NULL,
   BEGINTIME            DATETIME             NULL,
   PERTIMEID            INT                  NULL,
   AMTGOODS             DECIMAL(12,2)        NULL,
   AMTAR                DECIMAL(12,2)        NULL,
   AMTFR                DECIMAL(12,2)        NULL,
   INTEGRAL             DECIMAL(12,2)        NULL,
   CHECKOUTUPDATEDTIME  DATETIME             NULL,
   CHECKOUTTIME         DATETIME             NULL,
   AMTPAID              INT                  NULL,
   PEOPLE               INT                  NULL,
   USER_ID              VARCHAR(36)          NULL,
   TEL                  VARCHAR(50)          NULL,
   SALPROPERTY          INT                  NULL,
   STATUS               INT                  NULL,
   CREATED_BY           VARCHAR(36)          NULL,
   CREATED_TIME         DATETIME             NULL DEFAULT GETDATE(),
   LAST_UPDATED_BY      VARCHAR(36)          NULL,
   LAST_UPDATED_TIME    DATETIME             NULL DEFAULT GETDATE(),
   ORDER_DEVICE         VARCHAR(50)          NULL,
   CONSTRAINT PK_DINE_SALES PRIMARY KEY (SALESID)
)
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_SALES')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_SALES', 'column', 'CREATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '������',
   'user', @CURRENTUSER, 'table', 'DINE_SALES', 'column', 'CREATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_SALES')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_SALES', 'column', 'CREATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_SALES', 'column', 'CREATED_TIME'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_SALES')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_SALES', 'column', 'LAST_UPDATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸���',
   'user', @CURRENTUSER, 'table', 'DINE_SALES', 'column', 'LAST_UPDATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_SALES')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_SALES', 'column', 'LAST_UPDATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸�ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_SALES', 'column', 'LAST_UPDATED_TIME'
go

CREATE TABLE DINE_SALESDD (
   DETAIL_ID            VARCHAR(36)          NOT NULL,
   SALESID              VARCHAR(36)          NULL,
   GOODSNO              INT                  NULL,
   GOODSID              VARCHAR(36)          NULL,
   GOODSNAME            VARCHAR(50)          NULL,
   CLASSID              VARCHAR(50)          NULL,
   UNIT                 VARCHAR(50)          NULL,
   PRICE                DECIMAL(12,2)        NULL,
   QTY                  DECIMAL(12,2)        NULL,
   AMTAR                DECIMAL(12,2)        NULL,
   AMTFR                DECIMAL(12,2)        NULL,
   INPUTTIME            DATETIME             NULL,
   NOTE                 VARCHAR(40)          NULL,
   MEALSETFLAG          INT                  NULL,
   STATUS               INT                  NULL,
   CREATED_BY           VARCHAR(36)          NULL,
   CREATED_TIME         DATETIME             NULL DEFAULT GETDATE(),
   LAST_UPDATED_BY      VARCHAR(36)          NULL,
   LAST_UPDATED_TIME    DATETIME             NULL DEFAULT GETDATE(),
   CONSTRAINT PK_DINE_SALESDD PRIMARY KEY (DETAIL_ID)
)
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_SALESDD')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_SALESDD', 'column', 'CREATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '������',
   'user', @CURRENTUSER, 'table', 'DINE_SALESDD', 'column', 'CREATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_SALESDD')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'CREATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_SALESDD', 'column', 'CREATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_SALESDD', 'column', 'CREATED_TIME'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_SALESDD')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_BY')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_SALESDD', 'column', 'LAST_UPDATED_BY'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸���',
   'user', @CURRENTUSER, 'table', 'DINE_SALESDD', 'column', 'LAST_UPDATED_BY'
go

IF EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE
      P.MAJOR_ID = OBJECT_ID('DINE_SALESDD')
  AND P.MINOR_ID = (SELECT C.COLUMN_ID FROM SYS.COLUMNS C WHERE C.OBJECT_ID = P.MAJOR_ID AND C.NAME = 'LAST_UPDATED_TIME')
)
BEGIN
   DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_DROPEXTENDEDPROPERTY 'MS_Description', 
   'user', @CURRENTUSER, 'table', 'DINE_SALESDD', 'column', 'LAST_UPDATED_TIME'

END


SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '����޸�ʱ��',
   'user', @CURRENTUSER, 'table', 'DINE_SALESDD', 'column', 'LAST_UPDATED_TIME'
go
/*
insert into Dine_sales ( SALESID, Dine_ID, SALESCODE, BEGINDate, BEGINTIME, PERTIMEID, AMTGOODS, AMTAR, AMTFR, integral, CHECKOUTUPDATEDTIME, CHECKOUTTIME, AMTPAID, PEOPLE, USER_ID, TEL, SalProperty, Status, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME, Order_Device )
values ( '11111111', '01', '11111111', '2018-11-24', '2018-11-24 18:30:30', 3, 100.00, 80.00, 80.00, 0.00, '2018-11-24 18:30:30', '2018-11-24 18:30:30', 80.00, 2, null, '13844446666', 1, 1, '0001', '2018-11-24 18:30:30', '0001', '2018-11-24 18:30:30', 'APP' )
insert into Dine_salesdd ( Detail_ID, SALESID, GOODSNO, goodsid, GOODSNAME, CLASSID, UNIT, PRICE, QTY, AMTAR, AMTFR, INPUTTIME, NOTE, MEALSETFLAG, Status, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME )
values ( '01', '11111111', 1, '10001', '焖鲈鱼', '01_10', '锅', 125.00, 1.00, 125.00, 80.00, '2018-11-24 18:30:30', null, 0, 1, '0001', '2018-11-24 18:30:30', '0001', '2018-11-24 18:30:30' )

insert into Dine_sales ( SALESID, Dine_ID, SALESCODE, BEGINDate, BEGINTIME, PERTIMEID, AMTGOODS, AMTAR, AMTFR, integral, CHECKOUTUPDATEDTIME, CHECKOUTTIME, AMTPAID, PEOPLE, USER_ID, TEL, SalProperty, Status, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME, Order_Device )
values ( '22222222', '01', '22222222', '2018-11-24', '2018-11-24 18:30:30', 3, 120.00, 100.00, 100.00, 0.00, '2018-11-24 18:30:30', '2018-11-24 18:30:30', 100.00, 2, null, '13844446666', 1, 1, '0001', '2018-11-24 18:30:30', '0001', '2018-11-24 18:30:30', 'APP' )
insert into Dine_salesdd ( Detail_ID, SALESID, GOODSNO, goodsid, GOODSNAME, CLASSID, UNIT, PRICE, QTY, AMTAR, AMTFR, INPUTTIME, NOTE, MEALSETFLAG, Status, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME )
values ( '02', '22222222', 1, '10001', '焖鲈鱼', '01_10', '锅', 120.00, 1.00, 120.00, 100.00, '2018-11-24 18:30:30', null, 0, 1, '0001', '2018-11-24 18:30:30', '0001', '2018-11-24 18:30:30' )

insert into Dine_sales ( SALESID, Dine_ID, SALESCODE, BEGINDate, BEGINTIME, PERTIMEID, AMTGOODS, AMTAR, AMTFR, integral, CHECKOUTUPDATEDTIME, CHECKOUTTIME, AMTPAID, PEOPLE, USER_ID, TEL, SalProperty, Status, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME, Order_Device )
values ( '33333333', '01', '33333333', '2018-11-24', '2018-11-24 18:30:30', 3, 120.00, 100.00, 100.00, 0.00, '2018-11-24 18:30:30', '2018-11-24 18:30:30', 100.00, 2, null, '13844446666', 1, 1, '0001', '2018-11-24 18:30:30', '0001', '2018-11-24 18:30:30', 'APP' )
insert into Dine_salesdd ( Detail_ID, SALESID, GOODSNO, goodsid, GOODSNAME, CLASSID, UNIT, PRICE, QTY, AMTAR, AMTFR, INPUTTIME, NOTE, MEALSETFLAG, Status, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME )
values ( '03', '33333333', 1, '10001', '焖鲈鱼', '01_10', '锅', 120.00, 1.00, 120.00, 100.00, '2018-11-24 18:30:30', null, 0, 1, '0001', '2018-11-24 18:30:30', '0001', '2018-11-24 18:30:30' )
go
*/
ALTER TABLE DINE_GOODSBOM
   ADD CONSTRAINT FK_GOODSBOM_REFERENCE_GOODS FOREIGN KEY (GOODSID)
      REFERENCES DINE_GOODS (GOODSID)
go

ALTER TABLE DINE_GOODS
   ADD CONSTRAINT FK_GOODS_REFERENCE_GOODSCLS FOREIGN KEY (CLASSID)
      REFERENCES DINE_CLASSSUB (CLASSID)
go

ALTER TABLE DINE_GOODS_TYPE_REL
   ADD CONSTRAINT FK_GOODSCLSREL_REFERENCE_DINE_GOODS FOREIGN KEY (GOODSID)
      REFERENCES DINE_GOODS (GOODSID)
go

ALTER TABLE DINE_GOODS_TYPE_REL
   ADD CONSTRAINT FK_GOODSCLSREL_REFERENCE_GOODSCLS FOREIGN KEY (TYPEID)
      REFERENCES DINE_GOODS_TYPE (TYPEID)
go

ALTER TABLE DINE_SALESDD
   ADD CONSTRAINT FK_BILLGOODS_REFERENCE_BILL FOREIGN KEY (SALESID)
      REFERENCES DINE_SALES (SALESID)
go

ALTER TABLE DINE_SALESDD
   ADD CONSTRAINT FK_BILLGOODS_REFERENCE_GOODS FOREIGN KEY (GOODSID)
      REFERENCES DINE_GOODS (GOODSID)
go

