"""empty message

Revision ID: 2c4c80e6d8c8
Revises: 
Create Date: 2023-03-17 15:57:38.771983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c4c80e6d8c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='类别名称'),
    sa.Column('order_num', sa.Integer(), server_default=sa.text('10'), nullable=False, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:无效 1:正常'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('organization', sa.Integer(), nullable=False, comment='所属组织'),
    sa.Column('incharge', sa.Integer(), nullable=True, comment='负责人'),
    sa.Column('order_number', sa.Integer(), server_default=sa.text('10'), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:未激活 1:正常 9:失效'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('code', sa.String(length=20), nullable=True, comment='商品代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('category', sa.Integer(), nullable=False, comment='类别'),
    sa.Column('category_name', sa.String(length=20), nullable=False, comment='类别名称'),
    sa.Column('supplier', sa.Integer(), nullable=False, comment='供应商'),
    sa.Column('supplier_name', sa.String(length=50), nullable=False, comment='供应商名称'),
    sa.Column('model', sa.String(length=20), nullable=True, comment='型号'),
    sa.Column('image', sa.String(length=100), nullable=True, comment='图片'),
    sa.Column('order_num', sa.Integer(), server_default=sa.text('10'), nullable=False, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:无效 1:正常'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('simple_name', sa.String(length=20), nullable=False, comment='简称'),
    sa.Column('order_number', sa.Integer(), server_default=sa.text('10'), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:未激活 1:正常 9:失效'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('simple_name')
    )
    op.create_table('organizationfuncs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('organization', sa.Integer(), nullable=True, comment='组织'),
    sa.Column('fuction', sa.Integer(), nullable=True, comment='功能'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('sex', sa.Integer(), nullable=True, comment='性别 0:女 1:男'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='e-mail地址'),
    sa.Column('department', sa.Integer(), nullable=False, comment='所属部门'),
    sa.Column('account', sa.Integer(), nullable=True, comment='账号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='状态 0:未转正 1:正式 9:已离职'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='供应商名称'),
    sa.Column('simple_name', sa.String(length=20), nullable=False, comment='简称'),
    sa.Column('code', sa.String(length=20), nullable=True, comment='代码'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:无效 1:正常'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sysapp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('order_number', sa.Integer(), server_default=sa.text('10'), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:未激活 1:正常 9:失效'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sysauthorization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('user', sa.Integer(), nullable=False, comment='用户'),
    sa.Column('sysrole', sa.Integer(), nullable=False, comment='角色'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sysfunction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('sysmodel', sa.Integer(), nullable=False, comment='所属模块'),
    sa.Column('authorizate_flag', sa.Integer(), server_default=sa.text('1'), nullable=True, comment='是否需要授权'),
    sa.Column('order_number', sa.Integer(), server_default=sa.text('10'), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:未激活 1:正常 9:失效'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sysmodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='名称'),
    sa.Column('sysapp', sa.Integer(), nullable=False, comment='所属应用'),
    sa.Column('order_number', sa.Integer(), server_default=sa.text('10'), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:未激活 1:正常 9:失效'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sysoperation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('sysfunction', sa.Integer(), nullable=False, comment='所属功能'),
    sa.Column('order_number', sa.Integer(), server_default=sa.text('10'), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:未激活 1:正常 9:失效'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('syspermission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('sysrole', sa.Integer(), nullable=False, comment='角色'),
    sa.Column('sysoperation', sa.Integer(), nullable=False, comment='权限'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sysrole',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('order_number', sa.Integer(), server_default=sa.text('10'), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='状态 0:未激活 1:正常 9:失效'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=mysql.INTEGER(),
               server_default=sa.text('1'),
               existing_comment='来源 0:内部员工 1:主动注册 2:第三方引入',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               server_default=sa.text('1'),
               existing_comment='状态 0:未激活 1:正常 2:被冻结 9:已注销',
               existing_nullable=False)
        batch_op.alter_column('created_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('updated_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='状态 0:未激活 1:正常 2:被冻结 9:已注销',
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='来源 0:内部员工 1:主动注册 2:第三方引入',
               existing_nullable=False)

    op.drop_table('sysrole')
    op.drop_table('syspermission')
    op.drop_table('sysoperation')
    op.drop_table('sysmodel')
    op.drop_table('sysfunction')
    op.drop_table('sysauthorization')
    op.drop_table('sysapp')
    op.drop_table('supplier')
    op.drop_table('staff')
    op.drop_table('organizationfuncs')
    op.drop_table('organization')
    op.drop_table('goods')
    op.drop_table('department')
    op.drop_table('category')
    # ### end Alembic commands ###
