"""empty message

Revision ID: 60b589890ec8
Revises: 
Create Date: 2023-03-11 16:32:00.825430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60b589890ec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('category')
    # op.drop_table('supplier')
    # op.drop_table('goods')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='状态 0:未激活 1:正常 2:被冻结 9:已注销',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('updated_time',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='用户'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        'user',
        '用户',
        existing_comment=None,
        schema=None
    )
        batch_op.alter_column('updated_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='状态 0:未激活 1:正常 2:被冻结 9:已注销',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    op.create_table('goods',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='ID，自增主键'),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False, comment='商品代码'),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False, comment='商品名称'),
    sa.Column('category', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='商品类别'),
    sa.Column('category_name', mysql.VARCHAR(length=50), nullable=False, comment='类别名称'),
    sa.Column('supplier', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='供应商ID'),
    sa.Column('supplier_name', mysql.VARCHAR(length=50), nullable=False, comment='供应商名称'),
    sa.Column('model', mysql.VARCHAR(length=20), nullable=True, comment='型号'),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True, comment='商品图片（地址）'),
    sa.Column('order_num', mysql.INTEGER(), server_default=sa.text("'100'"), autoincrement=False, nullable=False, comment='排序号'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='状态 0:下架 1:上架 2:停售'),
    sa.Column('remark', mysql.VARCHAR(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('supplier',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False, comment='名称'),
    sa.Column('simple_name', mysql.VARCHAR(length=50), nullable=False, comment='简称'),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=True, comment='代码'),
    sa.Column('status', mysql.TINYINT(unsigned=True), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态 0:无效 1:正常'),
    sa.Column('remark', mysql.VARCHAR(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='供应商',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='供应商',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False, comment='类别名称'),
    sa.Column('order_num', mysql.INTEGER(), server_default=sa.text("'100'"), autoincrement=False, nullable=False, comment='排序号'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态 0:无效 1:正常'),
    sa.Column('remark', mysql.VARCHAR(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='商品类别',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='商品类别',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
