"""empty message

Revision ID: 80e065573c47
Revises: 60b589890ec8
Create Date: 2023-03-14 17:36:37.921861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e065573c47'
down_revision = '60b589890ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='类别名称'),
    sa.Column('order_num', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态 0:无效 1:正常'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('code', sa.String(length=20), nullable=True, comment='商品代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('category', sa.Integer(), nullable=False, comment='类别'),
    sa.Column('category_name', sa.String(length=20), nullable=False, comment='类别名称'),
    sa.Column('supplier', sa.Integer(), nullable=False, comment='供应商'),
    sa.Column('supplier_name', sa.String(length=50), nullable=False, comment='供应商名称'),
    sa.Column('model', sa.String(length=20), nullable=True, comment='型号'),
    sa.Column('image', sa.String(length=100), nullable=True, comment='图片'),
    sa.Column('order_num', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态 0:无效 1:正常'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='供应商名称'),
    sa.Column('simple_name', sa.String(length=20), nullable=False, comment='简称'),
    sa.Column('code', sa.String(length=20), nullable=True, comment='代码'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态 0:无效 1:正常'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier')
    op.drop_table('goods')
    op.drop_table('category')
    # ### end Alembic commands ###
